fixes doc linting error: redundant explicit link target
error: redundant explicit link target
  --> scylla/src/lib.rs:16:55
   |
16 | //! All driver activity revolves around the [Session](crate::Session)\
   |                                              -------  ^^^^^^^^^^^^^^ explicit target is redundant
   |                                              |
   |                                              because label contains path that resolves to same destination
   |
   = note: when a link's destination is not specified,
           the label is used to resolve intra-doc links
   = note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
help: remove explicit link target

fixes: https://github.com/scylladb/scylla-rust-driver/issues/847