SerializationError: dyn Error instead of dyn Any
Error needs to be dynamic, so that users can use their own types, but
at the same time allow it to be stored in concrete type (like `QueryError`).
`dyn Error` supports downcasting, so it can be used instead of `Any`.