examples/execution_profile: fix usage of illegal consistency
The example in `execution_profile.rs` tried to send a read request
using consistency `EACH_QUORUM`.
This doesn't work, the query failed with the following message:
```
Error: Database returned an error: The query is syntactically correct but invalid, Error message: EACH_QUORUM ConsistencyLevel is only supported for writes
```
Examples shouldn't fail. Let's fix it by changing `EachQuorum`
to `LocalQuorum` which can be used in SELECTs.
After this change the example doesn't fail.

It still demonstrates how to create an execution profile
with a custom consistency level, it doesn't matter what consistency level is used.

Fixes: https://github.com/scylladb/scylla-rust-driver/issues/835

Signed-off-by: Jan Ciolek <jan.ciolek@scylladb.com>