error: add TranslationError::NoRuleForHost
If an address translator looks up translation rules by host id, it might
fail to find it. For such case, the new variant is introduced. It's
potentially useful for cases different than PrivateLink, so it's not
guarded by any `cfg(feature)`.

Note that after changes to the original approach, the variant is no
longer used in the code. However, it might be useful in the future, so
I keep the commit. Reviewers are welcome to suggest if it should be kept
or dropped.