RowsParseError: add variant for TypeCheckError
When parsing rows, type check is a distinct phase in the new
deserialization framework. To support propagation of errors related to
type checking, a corresponding variant is added to RowsParseError.