TryFromPrimitiveError: Add public constructor
This type will have to be moved to scylla-cql-core, but also constructed
in scylla-cql. I prefer adding a constructor rather than publishing
fields, because we could potentially add new fields in the future, by
default-initializing them in this constructor.