ColumnSpecParseError: Add pub constructor
As part of scylla-cql-core split, we need to move frame_errors to core.
scylla-cql needs to be able to construct ColumnSpecParseError. It is
non_exhaustive, so we need to either make it exhaustive, or add a
constructor. Constructor is imo mor future-proof, because if we need to
add new fields, we can add new constructor, and make this one put some
default values for the new fields.