examples: fix clippy's complaints about redundant_locals
Rust 1.73 got released very recently and introduced a new version of
clippy, with new lints. The `parallel` and `parallel-prepared` examples
contain code which redefines a local variable:

```
for i in 0..100_000usize {
    // ...
    tokio::task::spawn(async move {
        let i = i;
        // ...
    });
}
```

This is completely unnecesary and can be removed, as per clippy's
suggestion:

```
error: redundant redefinition of a binding
  --> examples/parallel-prepared.rs:36:9
   |
36 |     for i in 0..100_000usize {
   |         ^
...
44 |             let i = i;
   |             ^^^^^^^^^^
   |
   = help: remove the redefinition of `i`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
   = note: `#[deny(clippy::redundant_locals)]` on by default
```